### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by davetcoleman** [moveit/warehouse_ros_mongo#7]
When building this package's tests this error occurs: https://gist.github.com/davetcoleman/f5dddabaa85c373f61cd2a906170a956

**Comment by christian-rauch** [comment]
This issue should be resolved. Since commit 68fc7fc33a1ce6662a4d0607ccbd0d04ed57b18e the tests build successfully.
@rhaschke Can we close this?

**Comment by rhaschke** [comment]
They are still not executed on Travis. Hence, they don't yet act as unittests.
I need some more hints how to setup a mongodb server via cmdline.

**Comment by rhaschke** [comment]
> I need some more hints how to setup a mongodb server via cmdline.

@christian-rauch, could you help on this?

**Comment by christian-rauch** [comment]
I lost track of this issue. The tests are not executed because MongoDB ist missing in the Docker container? Is there a warning or info message about this in the CI log?

At least on melodic, I just installed packages `mongodb-server` and `mongodb-clients` via apt. The manual installation of `mongo-cxx-driver` via the `travis.before_script` script was not required.

**Comment by rhaschke** [comment]
Installing packages works fine, I think. Does this automatically run the server as well?

**Comment by christian-rauch** [comment]
I think Debian autostarts services after package installation. Also, I don't recall that I manually started the service.

**Comment by rhaschke** [comment]
Ok. Then I need to have a look at the error once again...

**Comment by rhaschke** [comment]
I think I found the culprit:
```
Setting up mongodb-server (1:3.6.3-0ubuntu1.1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
```
Looks like `mongodb-server` is not automatically started within the docker container.
I'm working on a solution.

**Comment by rhaschke** [comment]
Fixed via #27.

**Comment by christian-rauch** [comment]
How was this fixed in the end if #27 is closed without merging?

**Comment by rhaschke** [comment]
I manually merged #27 and github didn't noticed.
